<div class="s-prose s-prose__disable-spoiler-hover js-post-body" itemprop="text">
<h1>TL; DR</h1>

<p>Basically, all of your <code>except</code> blocks are "defaults", hence the error message. To have multiple <code>except</code> clauses, you must tell to all of them (except the last one) what they're supposed to catch (what used functions can - and will - raise)</p>

<h1>What's happening ?</h1>

<p>The reason is quite simple here. </p>

<p><code>try..except</code> blocks can accept many <code>except</code> blocks in order to do things in case of different type of exceptions. By default (and I don't really recommend it, because you don't have a clear idea of what's going on) it's a block like this one:</p>

<pre><code>try:
    i_will_raise_some_exception()
except:
    # fix me up before you go!
</code></pre>

<p>This will catch every exception raised because we didn't tell the except block what to catch. You might already understand your problem here. Here's a second example:</p>

<pre><code>try:
    # I used this condition to have a somewhat believable (yet dumb) way to say
    # I can send multiple exceptions within the same try block
    if (some_weird_condition):
        print(1/0)
    i_will_raise_some_exception()

except DivisionError:
    # woops!

# Exception is optional here, as it catches everything
except Exception:
    # catch any other exceptions and fix me up before you go!
</code></pre>

<p>You can find more information <a href="https://docs.python.org/3.7/tutorial/errors.html#handling-exceptions" rel="nofollow noreferrer">here</a>.</p>
    </div>